### ISSUE TITLE
System.Collections with vNext

### ISSUE THREAD

**Issue by pierregaboriaud** [Mangopay/mangopay2-net-sdk#20] opened 2016-06-16 01:17 UTC
Hello !

I have another error when I call the api : 

>  {"Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.":"System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"}.

Exception Data : {System.Collections.ListDictionaryInternal}

```
at MangoPay.SDK.Core.RestTool.DoRequestList[T](String urlMethod, Pagination pagination, Dictionary`2 additionalUrlParams)
at MangoPay.SDK.Core.RestTool.RequestList[T](String urlMethod, String requestType, Dictionary`2 requestData, Pagination pagination, Dictionary`2 additionalUrlParams)
at MangoPay.SDK.Core.RestTool.RequestList[T](String urlMethod, String requestType, Dictionary`2 requestData, Pagination pagination)
at MangoPay.SDK.Core.APIs.ApiBase.GetList[T](MethodKey methodKey, Pagination pagination, String entityId, String secondEntityId, Sort sort, Dictionary`2 additionalUrlParams)
at MangoPay.SDK.Core.APIs.ApiUsers.GetAll()
```

Thank you for your help

**Comment by hobailey** [comment] 2016-06-16 07:20
Hi @pierregaboriaud - could your provide the code sample that reproduces this please?

**Comment by pierregaboriaud** [comment] 2016-06-16 13:01
hi @hobailey,

```
_api = new MangoPayApi();
_api.Config.ClientId = _clientId;
_api.Config.ClientPassword = _clientPass;
_api.Config.BaseUrl = _url;

_api.Users.GetAll();
```

Environnement : vNext RC2 with support .net451, Visual Studio 2015

**Comment by hobailey** [comment] 2016-07-25 17:19
Hey @pierregaboriaud, sorry for the delay with this - are you still experiencing the problem? I wonder if it was just cache related or something? I can't reproduce it with VS 2015 :-/

**Comment by pierregaboriaud** [comment] 2016-07-25 22:00
Hey,

I stopped using your library for that and I make calls to your API manually with no troubles.

Have you try to compile with dotnetcore and  CLI to reproduced my error ?
https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/

**Comment by hobailey** [comment] 2016-09-26 14:53
So we're unable to reproduce your problem I'm afraid, even trying as you suggested in your last comment. Either way, System.dll is part of the framework so we're not sure why your build is not picking it up :-/ 
I'm therefore going to close this for now, but do let us know if you manage to make any progress. Thanks.

**Closed by hobailey** 2016-09-26 14:53 UTC
